version: v1
resource: cluster
meta:
  vars: {}
  roles:
    - name: master
      vars: {}
      requires:
        - name: volume
          minimal: 50
          excellent: 100
        - name: cpu
          minimal: 2
          excellent: 4
        - name: memory
          minimal: 4
          excellent: 16
    - name: worker
      vars: {}
      requires:
        - name: volume
          minimal: 50
          excellent: 100
        - name: cpu
          minimal: 2
          excellent: 4
        - name: memory
          minimal: 4
          excellent: 16
    - name: router
      vars: {}
      requires:
        - name: volume
          minimal: 50
          excellent: 100
        - name: cpu
          minimal: 2
          excellent: 4
        - name: memory
          minimal: 4
          excellent: 16
