version: v1
cni:
  - name: flannel
    vars:
      CLUSTER_NETWORK: flannel
storage:
  - name: nfs
    vars:
      storage_nfs_enabled: true
      storage_nfs_provisioner_name: nfs-provisioner
cluster:
  vars: {}
  roles:
    - name: master
      vars: {}
      requires:
        - name: volume
          minimal: 50
          excellent: 100
        - name: cpu
          minimal: 2
          excellent: 4
        - name: memory
          minimal: 4
          excellent: 16
    - name: worker
      vars: {}
      requires:
        - name: volume
          minimal: 50
          excellent: 100
        - name: cpu
          minimal: 2
          excellent: 4
        - name: memory
          minimal: 4
          excellent: 16
    - name: router
      vars: {}
      requires:
        - name: volume
          minimal: 50
          excellent: 100
        - name: cpu
          minimal: 2
          excellent: 4
        - name: memory
          minimal: 4
          excellent: 16
    - name: loadblance
      vars: {}
      requires:
        - name: volume
          minimal: 50
          excellent: 100
        - name: cpu
          minimal: 2
          excellent: 4
        - name: memory
          minimal: 4
          excellent: 16
